### ISSUE TITLE
Mod names duplicated

### ISSUE THREAD

**Issue by KAJed82** [X2CommunityCore/xcom2-launcher#64] opened 2019-01-28 17:57 UTC
I'm having issues with all of my mods switching their names / other meta data with something else. I now have mutliple instance of all of my mods although their IDs have not changed. I tried removing them from steam and re-installing them to no avail. It seems as though there is a cache somewhere that it keeps using.

Additionally whenever I run the launch Steam gets confused and forces me to re-login constantly.

**Comment by Dragon-32** [comment] 2019-01-29 18:13
Could be the db got screwed up, try deleting:
XCOM 2 Mod Launcher\settings.json

Take a backup first as you'll lose all your load order and mod groupings and other settings.

**Comment by KAJed82** [comment] 2019-01-29 21:19
I did, repeatedly. The same screw up happened regardless. Also tried to redownload all my mods through steam. So far the only fix I’ve had is running the debug version (built manually in VS2017) and that seems to fix it for now. Running the release build from Github again has the same issue. 

I cannot confirm right this moment if self built release works or not but I believe when I attempted it it exhibited the same issues. 

If I get a chance I may try running release with debug symbols and see if I can’t figure out what’s causing the issue.

**Comment by RevZero** [comment] 2019-06-10 11:15
@KAJed82 Did you figure this out?

**Comment by KAJed82** [comment] 2019-06-10 12:17
Unfortunately not. I ended up clearing everything and starting over and it went away.

**Comment by RevZero** [comment] 2019-06-10 12:21
Thanks for the response, so it seems there was something messed up on your side. I will consider this closed this then.

**Closed by RevZero** 2019-06-10 12:21 UTC
Labels: Status: Review, Type: Bug

**Comment by nlysne** [comment] 2020-03-02 05:45
Thought I would add an update here; 

I had the same issues as descried by KAJed82. It was caused by running Steam in Offline mode. For some reason the update process fails when Steam is offline and begins to write duplicate names / authors / etc over many different entries. Restarting Steam online then launching AML and letting it update solves the issue.

**Comment by RevZero** [comment] 2020-03-02 08:46
I can kind of reproduce this with AML v1.3.2. 
- Subscribe to one or more new mods in Steam workshop
- Go offline
- Start AML
- AML will find the new mods but the mod name and author information is wrong (duplicate of some other mod)

Maybe this can also happens for existing mods (not only newly added).

However, I am pretty sure this should be fixed with the changes in #175.  [AML 1.4.0-alpha](https://github.com/X2CommunityCore/xcom2-launcher/files/4189078/XCOM2_AlternativeModLauncher_1.4.0-alpha.zip).
