### ISSUE TITLE
Does not work with GOG version of the game.

### ISSUE THREAD

**Issue by PetrusVermaak** [X2CommunityCore/xcom2-launcher#239] opened 2020-11-17 08:03 UTC
Can you please update so that it also works with GOG version of the game?

**Comment by RevZero** [comment] 2020-11-17 08:45
See https://github.com/X2CommunityCore/xcom2-launcher/issues/181#issuecomment-717062707

Duplicate of #181

**Closed by RevZero** 2020-11-17 08:45 UTC
