### ISSUE TITLE
Resetting the mod folder list

### ISSUE THREAD

**Issue by AmauryLepicard** [X2CommunityCore/xcom2-launcher#193] opened 2020-04-29 20:27 UTC
Hi there,
It seems AML doesn't respect the custom mod directories I added (for LWOTC).
Each time I launch the game, My Documents\my games\XCOM2 War of the Chosen\XComGame\Config\XComEngine.ini is modified with only this line:
ModRootDirs=F:\SteamLibrary\steamapps\workshop\content\268500\

All others ModRootDirs lines are erased.
I had to put this file in read-only mode to be able to play my LWOTC campaign again.

Sorry if i'm not clear

**Comment by RevZero** [comment] 2020-04-29 20:29
I am looking into some issues with v1.4.0-beta right at this moment. Are you using that version?

**Comment by AmauryLepicard** [comment] 2020-04-29 20:31
Yeah I just updated to 1.4 beta indeed, and this bug appeared just after.

**Comment by RevZero** [comment] 2020-04-29 20:32
Duplicate of #194

**Closed** 2020-04-29 20:32 UTC

**Comment by RevZero** [comment] 2020-04-29 20:33
This is (hopefully) getting fixed pretty soon with 1.4.0-beta.2

**Comment by AmauryLepicard** [comment] 2020-04-29 20:34
Is there a way I can help? I'm hella rusty in C#, but maybe I can have a look?

**Comment by RevZero** [comment] 2020-04-29 20:34
Already found the issue, working on the update

**Comment by AmauryLepicard** [comment] 2020-04-29 20:35
Nice, thanks :)
