### ISSUE TITLE
Launching XCOM 2 from the Launcher does not enable controller version of Steam overlay

### ISSUE THREAD

**Issue by tunbridgep** [X2CommunityCore/xcom2-launcher#18] opened 2017-09-04 04:52 UTC
Launching XCOM 2 or War of the Chosen from the Alternative Mod Launcher does not allow the Steam Big-Picture version of the in-game overlay which is supposed to automatically replace the regular Steam overlay if a controller is detected. This is important because without the overlay, using custom controller configurations is impossible. This is relevant to any gamepad supported through Steam (Xbox 360 controller, dual shock 4, and Steam controller, as well as generic Xinput controllers) and is not specifically a Steam controller issue.

Repro:

1. Start the game normally through Steam with a controller active
2. The in-game Steam overlay can be activated through the guide button on the controller, and any controller configuration you have created in Steam will work
3. Start the game through the Launcher with a controller active
4. The regular in-game overlay will be used.
5. Steam will default to a useless default configuration for your controller and the guide button does nothing.

This issue isn't super important, but it would be nice to have a fix for it. I know I can just use the built-in game controller configuration, but it would be nice to have this option, especialy as many mods (Long War 2) completely break the in-game default controller support, and being able to rebind the stick to the arrow keys and the right stick to the mouse is a nice workaround for playing XCOM 2 with a controller and a lot of mods.

**Comment by mflux** [comment] 2018-10-03 03:15
I have this issue too. If I play XCom 2 from Steam Link, it uses big picture. Trying to play via the mod launcher can result in unstable controller configurations.

**Comment by RevZero** [comment] 2019-06-09 19:50
Duplicate of #42.

**Comment by RevZero** [comment] 2020-07-22 13:42
Close because this issue has already been referenced in a duplicate.

**Closed by RevZero** 2020-07-22 13:42 UTC
Labels: Status: Duplicate
