### ISSUE TITLE
Crashes when Steam is in Offline mode

### ISSUE THREAD

**Issue by pepoluan** [X2CommunityCore/xcom2-launcher#361] opened 2024-01-09 15:14 UTC
**AML Version:** 
1.5.0

**Description**
AML crashes -- or refuses to open -- on the following situations:
* Steam is in Offline mode
* Steam is in Online mode, but Internet connectivity is disturbed (laptop still connects to wifi but ISP is having problems)

This happened earlier today. Strangely, though, when I put Steam in Online mode for awhile, then turn it back to Offline mode, it doesn't crash again.

**Attachments**
* [AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/13875489/AML.log)
* [settings.json](https://github.com/X2CommunityCore/xcom2-launcher/files/13875493/settings.json)
* I have no screenshots because AML crashed. When the crash happened, AML did appear briefly, with controls partially rendered (some of them solid black), then it just closed itself after several seconds.

**Comment by RevZero** [comment] 2024-01-09 20:42
Judging from the logs, AML seems to crash silently. Probably caused by a task continuation or async void method where an unhandled Exception related to the failing Steam requests is happening.

**Comment by RevZero** [comment] 2024-11-14 10:47
I can not reproduce this with AML 1.6, so I will close this.

**Closed by RevZero** 2024-11-14 10:47 UTC
Labels: Type: Bug, Status: Accepted
