### ISSUE TITLE
Moved game files -> Dublicated IDs - Delete without unsubscribing.

### ISSUE THREAD

**Issue by Daraan** [X2CommunityCore/xcom2-launcher#207] opened 2020-06-01 14:10 UTC
Hey there. Thank you so much for this amazing tool!
----

I moved my game & mod files.

After setting up the locations (game folder was detected automatically) again, all Mods were flagged with the Dublicate ID error. Whole screen red.

The only way to resolve this via GUI seams to be the delete+unsubscribe option. Which will result in unsubscribing and deletion of mods/files that actually should be kept.

**Comment by RevZero** [comment] 2020-06-01 19:31
Thank you for reporting, we are aware of this, see #184.

Duplicate of #184.

**Closed by RevZero** 2020-06-01 19:31 UTC
