### ISSUE TITLE
AML closing after game launch

### ISSUE THREAD

**Issue by Phoenix4281** [X2CommunityCore/xcom2-launcher#378] opened 2024-05-29 13:15 UTC
**AML Version:** 
v1.5.0

**Description**
Whenever I launch WOTC, AML closes even though I have "Close after launch" unchecked.

**Attachments**
[AML.log](https://github.com/X2CommunityCore/xcom2-launcher/files/15484843/AML.log)
[settings.json](https://github.com/X2CommunityCore/xcom2-launcher/files/15484847/settings.json)

**Comment by Iridar** [comment] 2024-05-29 16:30
This is a duplicate of https://github.com/X2CommunityCore/xcom2-launcher/issues/317

**Comment by RevZero** [comment] 2024-05-30 12:22
"Resolved" does not mean that a potential fix has been merged and/or released. I get that the label "Resolved" may be misleading, so I renamed it to "implemented". The issue also targets milestone 1.6.

**Closed by RevZero** 2024-05-30 12:22 UTC
Labels: Type: Bug, Status: Review

**Comment by Phoenix4281** [comment] 2024-05-31 06:08
Ok thanks for letting me know. Sorry for the misunderstanding.
