### ISSUE TITLE
Xcom2-Launcher wont start

### ISSUE THREAD

**Issue by Frostyoi** [X2CommunityCore/xcom2-launcher#214] opened 2020-06-05 18:13 UTC
Hello

I am new user and as of today (2020-06/05) i cant launch the program annymore tried delting it and downlode it agine dident work, i found this error messege but i am sadly too stupid to understand it.

Sentry GUID: 8c6650a3-ea5c-4bf0-b48f-e794df3410e8
Message: Objektreferensen har inte angetts till en instans av ett objekt.
Stack: 
    vid XCOM2Launcher.Settings.FromFile(String file) i f:\AML\xcom2-launcher\xcom2-launcher\Classes\Settings.cs:rad 161
   vid XCOM2Launcher.Settings.get_Instance() i f:\AML\xcom2-launcher\xcom2-launcher\Classes\Settings.cs:rad 32
   vid XCOM2Launcher.Program.InitializeSettings() i f:\AML\xcom2-launcher\xcom2-launcher\Program.cs:rad 250
   vid XCOM2Launcher.Program.Main() i f:\AML\xcom2-launcher\xcom2-launcher\Program.cs:rad 89

if anyone can help me i wuld appriciate it.

**Comment by RevZero** [comment] 2020-06-05 18:47
Your settings file is probably invalid because AML failed to save it properly. Delete the `settings.json` in your AML folder to reset settings to default. This is a known issue. 

Duplicate of #206

**Closed** 2020-06-05 19:55 UTC
