### ISSUE TITLE
Not detecting path when game is installed on separate hard drive

### ISSUE THREAD

**Issue by BlueRaja** [X2CommunityCore/xcom2-launcher#188] opened 2020-04-24 07:39 UTC
With 1.3.2, it's not detecting the path automatically for me, even though it's less than 100 chars.  The path is `E:\Games\Steam\steamapps\common\XCOM 2`.  And even after I navigate to the XCom2 location (`E:\Games\Steam\steamapps\common\XCOM 2\XCom2-WarOfTheChosen\Binaries\Win64`) the app still fails to find anything.  I had to manually add the mod folders as well.

[Edit] Also, the launcher thinks I'm launching the Vanilla version, rather than WotC

**Comment by RevZero** [comment] 2020-04-24 14:44
Thanks for reporting.

If you manually specify the game path, you have to specify `E:\Games\Steam\steamapps\common\XCOM 2` without the `XCom2-WarOfTheChosen\Binaries\Win64`. 

However, AML sometimes not detecting the path is obviously an issue. Maybe you can help me to narrow the issue down by testing a pre-release version that performs some additional logging. I will inform you, when I actually have something that you could test.

**Comment by RevZero** [comment] 2020-05-01 18:34
Could you please try [AML 1.4.0-beta.2](https://github.com/X2CommunityCore/xcom2-launcher/releases/tag/v1.4.0-beta.2)?

* Extract into an empty folder 
* If it fails to detect game path, please post `AML.log` and `settings.json`

You can also visit our [Discord channel](https://discord.gg/QHSVGRn) and leave me a message there if you like.

**Comment by RevZero** [comment] 2020-06-07 21:35
Duplicate of #192

**Closed** 2020-06-07 21:35 UTC
Labels: Status: Feedback
